service: yancui-session-task-${self:custom.name}
frameworkVersion: "2 || 3"

custom:
  name: khaleeque
  email: kmem98@gmail.com

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-2
  profile: khaleeq

  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:scan
        - dynamodb:BatchWriteItem
      Resource: !GetAtt RestaurantsTable.Arn

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      restaurants_api: https://#{ApiGatewayRestApi}.execute-api.#{AWS::Region}.amazonaws.com/${self:provider.stage}/restaurants

  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants
          method: get
    environment:
      restaurants_table: !Ref RestaurantsTable

resources:
  Resources:
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH

  Outputs:
    RestaurantsTableName:
      Value: !Ref RestaurantsTable

plugins:
  - serverless-export-env
